# Data Manipulation and Analysis with Pandas

Data manipulation and analysis are key tasks in any data science or data analysis project. Pandas provides wide range of functions for data manipulation and analysis, making it easier to clean, transform and extract insights from data.

### Read the CSV file data

In [1]:
import pandas as pd

### Fetch the first 5 rows

In [2]:
df = pd.read_csv("data.csv")

# fetch the first 5 rows
df.head(5)

         Date Category  Value   Product  Sales Region
0  2025-01-01        C   11.9  Product3    NaN   West
1  2025-01-02        A   14.7  Product1  792.0   East
2  2025-01-03        C   42.3  Product1  195.0   West
3  2025-01-04        A   50.5  Product1  674.0   West
4  2025-01-05        C    NaN  Product3  529.0   West

### Fetch the last 5 rows

In [3]:
# fetch the last 5 rows
df.tail(5)

          Date Category  Value   Product  Sales Region
95  2025-04-06        C   84.1  Product3  407.0  North
96  2025-04-07        C   41.0  Product2  813.0  North
97  2025-04-08        C   13.5  Product2  780.0  South
98  2025-04-09      NaN   74.3  Product1  730.0  North
99  2025-04-10        B   54.7  Product1  411.0    NaN

### Statistical Summary

In [ ]:
# Statistical Summary
df.describe()

           Value       Sales
count  94.000000   93.000000
mean   49.154255  510.182796
std    28.979814  268.468966
min     1.300000  109.000000
25%    23.325000  261.000000
50%    50.650000  466.000000
75%    74.375000  779.000000
max    98.900000  999.000000

In [6]:
df.dtypes

Date            str
Category        str
Value       float64
Product         str
Sales       float64
Region          str
dtype: object

### Handling missing values

In [11]:
### Handling missing values

df[df.isnull()]         # True means missing values

   Date Category  Value Product  Sales Region
0   NaN      NaN    NaN     NaN    NaN    NaN
1   NaN      NaN    NaN     NaN    NaN    NaN
2   NaN      NaN    NaN     NaN    NaN    NaN
3   NaN      NaN    NaN     NaN    NaN    NaN
4   NaN      NaN    NaN     NaN    NaN    NaN
..  ...      ...    ...     ...    ...    ...
95  NaN      NaN    NaN     NaN    NaN    NaN
96  NaN      NaN    NaN     NaN    NaN    NaN
97  NaN      NaN    NaN     NaN    NaN    NaN
98  NaN      NaN    NaN     NaN    NaN    NaN
99  NaN      NaN    NaN     NaN    NaN    NaN

[100 rows x 6 columns]

In [12]:
df.isnull().any(axis=1)

0      True
1     False
2     False
3     False
4      True
      ...
95    False
96    False
97    False
98     True
99     True
Length: 100, dtype: bool

### Total missing values in each column

In [ ]:
# Total missing values in each column
df.isnull().sum()

Date        0
Category    5
Value       6
Product     5
Sales       7
Region      5
dtype: int64

### Fill all missing values

In [15]:
# Fill all missing values
df_filled = df.fillna(0)

### Fill missing values with the mean of the column

In [16]:
# Fill missing values with the mean of the column

df['Category_fillNA'] = df['Sales'].fillna(df['Sales'].mean())
df

          Date Category  Value   Product  Sales Region  Category_fillNA
0   2025-01-01        C   11.9  Product3    NaN   West       510.182796
1   2025-01-02        A   14.7  Product1  792.0   East       792.000000
2   2025-01-03        C   42.3  Product1  195.0   West       195.000000
3   2025-01-04        A   50.5  Product1  674.0   West       674.000000
4   2025-01-05        C    NaN  Product3  529.0   West       529.000000
..         ...      ...    ...       ...    ...    ...              ...
95  2025-04-06        C   84.1  Product3  407.0  North       407.000000
96  2025-04-07        C   41.0  Product2  813.0  North       813.000000
97  2025-04-08        C   13.5  Product2  780.0  South       780.000000
98  2025-04-09      NaN   74.3  Product1  730.0  North       730.000000
99  2025-04-10        B   54.7  Product1  411.0    NaN       411.000000

[100 rows x 7 columns]

In [17]:
df.dtypes

Date                   str
Category               str
Value              float64
Product                str
Sales              float64
Region                 str
Category_fillNA    float64
dtype: object

### Renaming columns

In [18]:
### Renaming columns

df = df.rename(columns= {'Date': 'Sales Date'})
df.head()

   Sales Date Category  Value   Product  Sales Region  Category_fillNA
0  2025-01-01        C   11.9  Product3    NaN   West       510.182796
1  2025-01-02        A   14.7  Product1  792.0   East       792.000000
2  2025-01-03        C   42.3  Product1  195.0   West       195.000000
3  2025-01-04        A   50.5  Product1  674.0   West       674.000000
4  2025-01-05        C    NaN  Product3  529.0   West       529.000000

### Change data types

In [20]:
### Change data types

df['Value_new'] = df['Value'].fillna(df['Value'].mean()).astype(int)
df.head()

,Sales Date,Category,Value,Product,Sales,Region,Category_fillNA,Value_new
0,2025-01-01,C,11.9,Product3,NaN,West,510.182796,11
1,2025-01-02,A,14.7,Product1,792.0,East,792.000000,14
2,2025-01-03,C,42.3,Product1,195.0,West,195.000000,42
3,2025-01-04,A,50.5,Product1,674.0,West,674.000000,50
4,2025-01-05,C,NaN,Product3,529.0,West,529.000000,49

In [21]:
df['New Value'] = df['Value'].apply(lambda x:x*2)
df.head()

,Sales Date,Category,Value,Product,Sales,Region,Category_fillNA,Value_new,New Value
0,2025-01-01,C,11.9,Product3,NaN,West,510.182796,11,23.8
1,2025-01-02,A,14.7,Product1,792.0,East,792.000000,14,29.4
2,2025-01-03,C,42.3,Product1,195.0,West,195.000000,42,84.6
3,2025-01-04,A,50.5,Product1,674.0,West,674.000000,50,101.0
4,2025-01-05,C,NaN,Product3,529.0,West,529.000000,49,NaN

### Data Aggregating and Grouping

In [22]:
### Data Aggregating and Grouping

df.head()

,Sales Date,Category,Value,Product,Sales,Region,Category_fillNA,Value_new,New Value
0,2025-01-01,C,11.9,Product3,NaN,West,510.182796,11,23.8
1,2025-01-02,A,14.7,Product1,792.0,East,792.000000,14,29.4
2,2025-01-03,C,42.3,Product1,195.0,West,195.000000,42,84.6
3,2025-01-04,A,50.5,Product1,674.0,West,674.000000,50,101.0
4,2025-01-05,C,NaN,Product3,529.0,West,529.000000,49,NaN

In [ ]:
grouped_mean = df.groupby('Product')['Value'].mean()
print(grouped_mean)

Product
Product1    53.242857
Product2    42.096296
Product3    52.333333
Name: Value, dtype: float64

### Grouping based on 2 categories - sum

In [ ]:
### Grouping based on 2 categories - sum

grouped_sum = df.groupby(['Product', 'Region'])['Value'].sum()
print(grouped_sum)

Product   Region
Product1  East      162.8
          North     362.3
          South     641.9
          West      622.2
Product2  East      259.9
          North     187.5
          South     253.5
          West      435.7
Product3  East      370.2
          North     579.0
          South     179.1
          West      206.7
Name: Value, dtype: float64

### Grouping based on 2 categories - mean

In [25]:
### Grouping based on 2 categories - mean

grouped_mean2 = df.groupby(['Product', 'Region'])['Value'].mean()
print(grouped_mean2)

Product   Region
Product1  East      32.560000
          North     51.757143
          South     64.190000
          West      56.563636
Product2  East      43.316667
          North     23.437500
          South     50.700000
          West      54.462500
Product3  East      74.040000
          North     52.636364
          South     35.820000
          West      51.675000
Name: Value, dtype: float64

### Aggregate multiple functions

In [26]:
### Aggregate multiple functions

grouped_agg = df.groupby('Region')['Value'].agg(['mean', 'sum', 'count'])
grouped_agg

             mean     sum  count
Region
East    48.570588   825.7     17
North   42.807407  1155.8     27
South   53.622727  1179.7     22
West    54.458333  1307.0     24

### Merging and Joining DataFrames

In [27]:
### Merging and Joining DataFrames

df1 = pd.DataFrame({'Key': ['A','B','C'], 'Value1': [1,2,3]})
df2 = pd.DataFrame({'Key': ['A','B','D'], 'Value2': [4,5,6]})

In [28]:
df1

  Key  Value1
0   A       1
1   B       2
2   C       3

In [29]:
df2

  Key  Value2
0   A       4
1   B       5
2   D       6

### Merge DataFrame on the 'Key Columns'

In [30]:
### Merge DataFrame on the 'Key Columns'

pd.merge(df1, df2, on="Key", how="inner")

  Key  Value1  Value2
0   A       1       4
1   B       2       5

In [31]:
pd.merge(df1, df2, on="Key", how="outer")

  Key  Value1  Value2
0   A     1.0     4.0
1   B     2.0     5.0
2   C     3.0     NaN
3   D     NaN     6.0

In [32]:
pd.merge(df1, df2, on="Key", how="left")

  Key  Value1  Value2
0   A       1     4.0
1   B       2     5.0
2   C       3     NaN

In [33]:
pd.merge(df1, df2, on="Key", how="right")

  Key  Value1  Value2
0   A     1.0       4
1   B     2.0       5
2   D     NaN       6