## Pandas - DataFrame and Series

Pandas is a powerful data manipulation library in Python, widely used for data analysis and data cleaning. It provides two primary data structures: Series and DataFrame.
Series is a one-dimensional array-like object.
DataFrame is a two-dimensional, size-mutable and potentially heterogenous tabular data structure with labeled axes (rows and columns).

In [1]:
import pandas as pd

### Create a Series

In [79]:
### Create a Series

import pandas as pd
data = [1,2,3,4,5]
series = pd.Series(data)
print("Series: \n", series)

Series:
 0    1
1    2
2    3
3    4
4    5
dtype: int64

### Create a Series from Dictionary

In [80]:
### Create a Series from Dictionary

data = {'a':1, 'b':2, 'c':3}
series_dict = pd.Series(data)
print(series_dict)

a    1
b    2
c    3
dtype: int64

In [81]:
data = [10,20,30]
index = ['a', 'b', 'c']
pd.Series(data, index)

a    10
b    20
c    30
dtype: int64

### Create a DataFrame from dictonary of list

In [82]:
### DataFrame

### Create a DataFrame from dictonary of list

data = {
    'Name': ['Dev', 'Ujjawal', 'Vaidik'],
    'Age': [22, 21, 20],
    'City': ['Mumbai', 'Bangalore', 'Pune']
}
df = pd.DataFrame(data)
print(df)
print(type(df))

      Name  Age       City
0      Dev   22     Mumbai
1  Ujjawal   21  Bangalore
2   Vaidik   20       Pune
<class 'pandas.DataFrame'>

In [83]:
import numpy as np
np.array(df)

array([['Dev', 22, 'Mumbai'],
       ['Ujjawal', 21, 'Bangalore'],
       ['Vaidik', 20, 'Pune']], dtype=object)

### Create a DataFrame from a list of Dictionaries

In [ ]:
### Create a DataFrame from a list of Dictionaries

data = [
    {'Name': 'Dev', 'Age': 22, 'City': 'Mumbai'},
    {'Name': 'Rishabh', 'Age': 21, 'City': 'Bangalore'},
    {'Name': 'Mreegendra', 'Age': 20, 'City': 'Kolkata'},
]
df = pd.DataFrame(data)
print(df)
print(type(df))

         Name  Age       City
0         Dev   22     Mumbai
1     Rishabh   21  Bangalore
2  Mreegendra   20    Kolkata
<class 'pandas.DataFrame'>

### Reading CSV file data

In [ ]:
### Reading CSV file data

df = pd.read_csv('Telecom_Usage.csv')
df.head(5)              # top 5 records

,Customer_ID,Days_Since_Last_Login,Avg_Time_Spent,Avg_Transaction_Value,avg_frequency_login_days,medium_of_operation,internet_option
0,fffe4300490044003600300030003800,17,300.63,53005.25,17,?,Wi-Fi
1,fffe43004900440032003100300035003700,16,306.34,12838.38,10,Desktop,Mobile_Data
2,fffe4300490044003100390032003600,14,516.16,21027.00,22,Desktop,Wi-Fi
3,fffe43004900440036003000330031003600,11,53.27,25239.56,6,Desktop,Mobile_Data
4,fffe43004900440031003900350030003600,20,113.13,24483.66,16,Smartphone,Mobile_Data

In [86]:
df.tail(5)              # last 5 records

,Customer_ID,Days_Since_Last_Login,Avg_Time_Spent,Avg_Transaction_Value,avg_frequency_login_days,medium_of_operation,internet_option
36987,fffe43004900440035003500390036003100,2,-650.682758,27277.68,6,Desktop,Wi-Fi
36988,fffe43004900440033003500380036003600,13,-638.123421,11069.71,28,Smartphone,Wi-Fi
36989,fffe4300490044003500330034003100,12,154.940000,38127.56,Error,Desktop,Wi-Fi
36990,fffe43004900440031003200390039003000,15,482.610000,2378.86,20,Smartphone,Mobile_Data
36991,fffe43004900440033003600340034003200,15,79.180000,2189.68,Error,Desktop,Mobile_Data

In [87]:
# Display the data types of each column
print("Data types:\n", df.dtypes)

# Describe the DataFrame
print("Statistical summary:\n", df.describe())

Data types:
 Customer_ID                     str
Days_Since_Last_Login         int64
Avg_Time_Spent              float64
Avg_Transaction_Value       float64
avg_frequency_login_days        str
medium_of_operation             str
internet_option                 str
dtype: object
Statistical summary:
        Days_Since_Last_Login  Avg_Time_Spent  Avg_Transaction_Value
count           36992.000000    36992.000000           36992.000000
mean              -41.915576      243.472334           29271.194003
std               228.819900      398.289149           19444.806226
min              -999.000000    -2814.109110             800.460000
25%                 8.000000       60.102500           14177.540000
50%                12.000000      161.765000           27554.485000
75%                16.000000      356.515000           40855.110000
max                26.000000     3235.578521           99914.050000

In [88]:
df.describe()

       Days_Since_Last_Login  Avg_Time_Spent  Avg_Transaction_Value
count           36992.000000    36992.000000           36992.000000
mean              -41.915576      243.472334           29271.194003
std               228.819900      398.289149           19444.806226
min              -999.000000    -2814.109110             800.460000
25%                 8.000000       60.102500           14177.540000
50%                12.000000      161.765000           27554.485000
75%                16.000000      356.515000           40855.110000
max                26.000000     3235.578521           99914.050000

### Accessing data from DataFrame

In [ ]:
### Accessing data from DataFrame
data = {
    'Name': ['Dev', 'Ujjawal', 'Vaidik'],
    'Age': [22, 21, 20],
    'City': ['Mumbai', 'Bangalore', 'Pune']
}
df = pd.DataFrame(data)
print(df)

      Name  Age       City
0      Dev   22     Mumbai
1  Ujjawal   21  Bangalore
2   Vaidik   20       Pune

In [ ]:
df['Name']

0        Dev
1    Ujjawal
2     Vaidik
Name: Name, dtype: str

In [ ]:
df.loc[0]          # row index

Name       Dev
Age         22
City    Mumbai
Name: 0, dtype: object

In [ ]:
df.loc[0, 'Name']

'Dev'

In [ ]:
df.iloc[0]       # column index

Name       Dev
Age         22
City    Mumbai
Name: 0, dtype: object

In [ ]:
df.iloc[0, 0]

'Dev'

In [ ]:
### Accessing a specified element using at

df.at[1, 'Age']

np.int64(21)

In [ ]:
### Accessing a specified element using iat

df.iat[2,2]

'Pune'

### Data Manipulation with DataFrame

In [ ]:
### Data Manipulation with DataFrame

df

      Name  Age       City
0      Dev   22     Mumbai
1  Ujjawal   21  Bangalore
2   Vaidik   20       Pune

In [ ]:
### Adding a column

df['Salary'] = [30000, 40000, 50000]
df

      Name  Age       City  Salary
0      Dev   22     Mumbai   30000
1  Ujjawal   21  Bangalore   40000
2   Vaidik   20       Pune   50000

In [ ]:
### Remove a column

df.drop('Salary', axis=1)         # axis=1 makes temporary removing a column

      Name  Age       City
0      Dev   22     Mumbai
1  Ujjawal   21  Bangalore
2   Vaidik   20       Pune

In [ ]:
df

      Name  Age       City  Salary
0      Dev   22     Mumbai   30000
1  Ujjawal   21  Bangalore   40000
2   Vaidik   20       Pune   50000

In [ ]:
### Remove a column permanently
df.drop('Salary', axis=1, inplace=True) 
df

      Name  Age       City
0      Dev   22     Mumbai
1  Ujjawal   21  Bangalore
2   Vaidik   20       Pune

In [ ]:
df

      Name  Age       City
0      Dev   22     Mumbai
1  Ujjawal   21  Bangalore
2   Vaidik   20       Pune

In [ ]:
### Increment age to the column

df['Age'] = df['Age'] + 1
df

      Name  Age       City
0      Dev   23     Mumbai
1  Ujjawal   22  Bangalore
2   Vaidik   21       Pune

In [ ]:
df.drop(0, inplace=True)
df

      Name  Age       City
1  Ujjawal   22  Bangalore
2   Vaidik   21       Pune